/*
 * data.js — Base de datos de pedales clásicos con sus listas de materiales (BOM).
 *
 * Las BOM son de referencia, basadas en los esquemáticos públicos más
 * difundidos (Electrosmash, General Guitar Gadgets, Tagboard Effects, etc.).
 * Distintas versiones/eras de un mismo pedal varían en algunos valores:
 * usá estas listas como guía y ajustalas a la versión que quieras armar.
 *
 * Tipos: resistor | capacitor | pot | transistor | ic | diode | led | hardware
 *  - resistor:  value en formato "4k7" / "4.7k" / "470" / "1M"
 *  - capacitor: value en formato "47n" / "2.2u" / "100p"
 *  - pot:       value "100k log" / "10k lin" / "100k dual"
 *  - transistor/ic/diode: número de parte ("2N3904", "JRC4558D", "1N4148")
 */
window.PEDAL_DB = {

  // Hardware común a casi cualquier build (opcional en el cálculo)
  hardware: [
    { type: "hardware", value: "caja 1590B", qty: 1 },
    { type: "hardware", value: "footswitch 3PDT", qty: 1 },
    { type: "hardware", value: "jack 6.35mm", qty: 2 },
    { type: "hardware", value: "jack DC 2.1mm", qty: 1 },
    { type: "led", value: "LED 5mm", qty: 1 },
  ],

  pedals: [
    {
      id: "bazz-fuss",
      name: "Bazz Fuss",
      brand: "DIY clásico",
      kind: "fuzz",
      difficulty: 1,
      description: "El fuzz más simple que existe: un transistor darlington y un puñado de componentes. Ideal como primer pedal.",
      circuit: [
        { type: "transistor", value: "MPSA13", qty: 1, note: "darlington NPN" },
        { type: "diode", value: "1N4148", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "pot", value: "100k log", qty: 1, note: "volumen" },
      ],
    },
    {
      id: "electra-distortion",
      name: "Electra Distortion",
      brand: "Electra",
      kind: "distorsión",
      difficulty: 1,
      description: "Distorsión de un transistor con recorte por diodos. Muy pocos componentes y suena sorprendentemente bien.",
      circuit: [
        { type: "transistor", value: "2N3904", qty: 1 },
        { type: "diode", value: "1N4148", qty: 2, note: "recorte (probá germanio o LEDs)" },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "2.2k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "pot", value: "100k log", qty: 1, note: "volumen" },
      ],
    },
    {
      id: "lpb-1",
      name: "LPB-1 Linear Power Booster",
      brand: "Electro-Harmonix",
      kind: "boost",
      difficulty: 1,
      description: "Booster lineal de un transistor. Empuja el frente del ampli o de otros pedales.",
      circuit: [
        { type: "transistor", value: "2N5088", qty: 1 },
        { type: "resistor", value: "430k", qty: 1 },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "390", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "pot", value: "100k lin", qty: 1, note: "boost" },
      ],
    },
    {
      id: "rangemaster",
      name: "Rangemaster Treble Booster",
      brand: "Dallas",
      kind: "boost",
      difficulty: 2,
      description: "Treble booster de germanio, el sonido de Brian May y Tony Iommi. Requiere un transistor de germanio con ganancia adecuada.",
      circuit: [
        { type: "transistor", value: "OC44", qty: 1, note: "PNP germanio (OC71/NKT275 sirven)" },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "68k", qty: 1 },
        { type: "resistor", value: "3.9k", qty: 1 },
        { type: "capacitor", value: "4.7n", qty: 1, note: "entrada, define el corte de graves" },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "47u", qty: 1, note: "electrolítico" },
        { type: "pot", value: "10k lin", qty: 1, note: "boost" },
      ],
    },
    {
      id: "fuzz-face",
      name: "Fuzz Face",
      brand: "Dallas Arbiter",
      kind: "fuzz",
      difficulty: 2,
      description: "El fuzz de Hendrix y Gilmour: dos transistores de germanio PNP. Simple de armar, exigente para bias y selección de transistores.",
      circuit: [
        { type: "transistor", value: "AC128", qty: 2, note: "PNP germanio (NKT275); versión silicio: BC108" },
        { type: "resistor", value: "33k", qty: 1 },
        { type: "resistor", value: "8.2k", qty: 1 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "resistor", value: "330", qty: 1 },
        { type: "capacitor", value: "2.2u", qty: 1 },
        { type: "capacitor", value: "22u", qty: 1, note: "electrolítico" },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "pot", value: "1k lin", qty: 1, note: "fuzz" },
        { type: "pot", value: "500k log", qty: 1, note: "volumen" },
      ],
    },
    {
      id: "mxr-distortion-plus",
      name: "Distortion+",
      brand: "MXR",
      kind: "distorsión",
      difficulty: 2,
      description: "Overdrive/distorsión de un opamp con recorte por diodos de germanio. El sonido de Randy Rhoads.",
      circuit: [
        { type: "ic", value: "LM741", qty: 1 },
        { type: "diode", value: "1N34A", qty: 2, note: "germanio (1N60 sirve)" },
        { type: "resistor", value: "1M", qty: 3 },
        { type: "resistor", value: "10k", qty: 2 },
        { type: "resistor", value: "4.7k", qty: 1 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "1n", qty: 1 },
        { type: "capacitor", value: "47n", qty: 1 },
        { type: "capacitor", value: "1u", qty: 2, note: "electrolítico" },
        { type: "pot", value: "500k rev", qty: 1, note: "distortion" },
        { type: "pot", value: "10k log", qty: 1, note: "output" },
      ],
    },
    {
      id: "tube-screamer-ts808",
      name: "Tube Screamer TS808",
      brand: "Ibanez",
      kind: "overdrive",
      difficulty: 3,
      description: "EL overdrive. Recorte simétrico en el lazo de realimentación de un JRC4558D y medios característicos.",
      circuit: [
        { type: "ic", value: "JRC4558D", qty: 1, note: "el 'chip mágico'; RC4558/TL072 funcionan" },
        { type: "transistor", value: "2SC1815", qty: 2, note: "buffers (2N3904 sirve)" },
        { type: "diode", value: "1N914", qty: 2, note: "recorte" },
        { type: "diode", value: "1N4001", qty: 1, note: "protección de polaridad" },
        { type: "resistor", value: "10k", qty: 6 },
        { type: "resistor", value: "4.7k", qty: 2 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "resistor", value: "510k", qty: 2 },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "resistor", value: "51k", qty: 1 },
        { type: "resistor", value: "220", qty: 1 },
        { type: "resistor", value: "470", qty: 1 },
        { type: "capacitor", value: "47n", qty: 2 },
        { type: "capacitor", value: "1u", qty: 3 },
        { type: "capacitor", value: "51p", qty: 1, note: "estabilidad" },
        { type: "capacitor", value: "220n", qty: 1 },
        { type: "capacitor", value: "100n", qty: 1 },
        { type: "capacitor", value: "10u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "47u", qty: 1, note: "electrolítico" },
        { type: "pot", value: "500k rev", qty: 1, note: "drive" },
        { type: "pot", value: "20k lin", qty: 1, note: "tone" },
        { type: "pot", value: "100k log", qty: 1, note: "level" },
      ],
    },
    {
      id: "proco-rat",
      name: "RAT",
      brand: "ProCo",
      kind: "distorsión",
      difficulty: 3,
      description: "Distorsión versátil alrededor del LM308 y su slew rate lento. Del crunch al fuzz con una perilla.",
      circuit: [
        { type: "ic", value: "LM308N", qty: 1, note: "OP07 es el reemplazo moderno" },
        { type: "transistor", value: "2N5458", qty: 1, note: "JFET, buffer de salida" },
        { type: "diode", value: "1N914", qty: 2, note: "recorte" },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "100k", qty: 2 },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "resistor", value: "560", qty: 1 },
        { type: "resistor", value: "47", qty: 1 },
        { type: "capacitor", value: "22n", qty: 2 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "2.2u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "1u", qty: 2 },
        { type: "capacitor", value: "4.7u", qty: 1, note: "electrolítico" },
        { type: "capacitor", value: "3.3n", qty: 1 },
        { type: "capacitor", value: "100p", qty: 1 },
        { type: "capacitor", value: "30p", qty: 1, note: "compensación" },
        { type: "pot", value: "100k log", qty: 1, note: "distortion" },
        { type: "pot", value: "100k lin", qty: 1, note: "filter" },
        { type: "pot", value: "100k log", qty: 1, note: "volume" },
      ],
    },
    {
      id: "big-muff-pi",
      name: "Big Muff Pi",
      brand: "Electro-Harmonix",
      kind: "fuzz",
      difficulty: 3,
      description: "Cuatro etapas de transistores con dos etapas de recorte. Sustain infinito, pared de fuzz. Muchos componentes pero todos comunes.",
      circuit: [
        { type: "transistor", value: "2N5088", qty: 4 },
        { type: "diode", value: "1N4148", qty: 4, note: "recorte (2 pares)" },
        { type: "resistor", value: "100k", qty: 6 },
        { type: "resistor", value: "470k", qty: 3 },
        { type: "resistor", value: "39k", qty: 2 },
        { type: "resistor", value: "12k", qty: 2 },
        { type: "resistor", value: "10k", qty: 4 },
        { type: "resistor", value: "22k", qty: 1 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "resistor", value: "330", qty: 1 },
        { type: "capacitor", value: "100n", qty: 5 },
        { type: "capacitor", value: "1u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "470p", qty: 3, note: "filtro de agudos en cada etapa" },
        { type: "capacitor", value: "4n", qty: 1, note: "tone stack (3.9n sirve)" },
        { type: "capacitor", value: "10n", qty: 1, note: "tone stack" },
        { type: "pot", value: "100k log", qty: 2, note: "sustain y volume" },
        { type: "pot", value: "100k lin", qty: 1, note: "tone" },
      ],
    },
    {
      id: "phase-90",
      name: "Phase 90",
      brand: "MXR",
      kind: "modulación",
      difficulty: 4,
      description: "Phaser de 4 etapas con JFETs como resistencias variables. Requiere matchear los 4 JFETs, pero el resultado vale la pena.",
      circuit: [
        { type: "transistor", value: "2N5952", qty: 4, note: "JFETs matcheados" },
        { type: "ic", value: "TL072", qty: 3, note: "originalmente opamps 741/4558" },
        { type: "resistor", value: "10k", qty: 8 },
        { type: "resistor", value: "24k", qty: 4, note: "etapas de fase" },
        { type: "resistor", value: "22k", qty: 2 },
        { type: "resistor", value: "150k", qty: 2 },
        { type: "resistor", value: "470k", qty: 2 },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "3.9M", qty: 5, note: "bias de los JFETs" },
        { type: "capacitor", value: "47n", qty: 4, note: "etapas de fase" },
        { type: "capacitor", value: "10u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "15u", qty: 1, note: "LFO (electrolítico)" },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "pot", value: "500k rev", qty: 1, note: "speed" },
      ],
    },
    {
      id: "klon-centaur",
      name: "Klon Centaur",
      brand: "Klon",
      kind: "overdrive",
      difficulty: 5,
      description: "El overdrive 'transparente' más mitificado. Charge pump a ±9V, mezcla de señal limpia y recortada con diodos de germanio.",
      circuit: [
        { type: "ic", value: "TL072", qty: 2 },
        { type: "ic", value: "TC1044SCPA", qty: 1, note: "charge pump (ICL7660S sirve)" },
        { type: "diode", value: "1N34A", qty: 2, note: "los famosos diodos de germanio" },
        { type: "diode", value: "1N5817", qty: 2, note: "schottky, fuente" },
        { type: "resistor", value: "10k", qty: 4 },
        { type: "resistor", value: "100k", qty: 5 },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "422k", qty: 1, note: "1% (un 470k aproxima)" },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "68k", qty: 1 },
        { type: "resistor", value: "22k", qty: 1 },
        { type: "resistor", value: "15k", qty: 1 },
        { type: "resistor", value: "5.6k", qty: 1 },
        { type: "resistor", value: "4.7k", qty: 1 },
        { type: "resistor", value: "1.5k", qty: 1 },
        { type: "resistor", value: "560", qty: 1 },
        { type: "capacitor", value: "100n", qty: 4 },
        { type: "capacitor", value: "1u", qty: 3 },
        { type: "capacitor", value: "4.7u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "47u", qty: 2, note: "electrolítico, charge pump" },
        { type: "capacitor", value: "68n", qty: 2 },
        { type: "capacitor", value: "390p", qty: 1 },
        { type: "capacitor", value: "820p", qty: 1 },
        { type: "pot", value: "100k dual", qty: 1, note: "gain (doble, curva especial)" },
        { type: "pot", value: "10k lin", qty: 1, note: "treble" },
        { type: "pot", value: "10k log", qty: 1, note: "output" },
      ],
    },
  ],
};
