/*
 * data.js — Base de datos de pedales clásicos con sus listas de materiales (BOM).
 *
 * Las BOM son de referencia, basadas en los esquemáticos públicos más
 * difundidos (Electrosmash, General Guitar Gadgets, Tagboard Effects, etc.).
 * Distintas versiones/eras de un mismo pedal varían en algunos valores:
 * usá estas listas como guía y ajustalas a la versión que quieras armar.
 *
 * Tipos: resistor | capacitor | pot | transistor | ic | diode | led | hardware
 *  - resistor:  value en formato "4k7" / "4.7k" / "470" / "1M"
 *  - capacitor: value en formato "47n" / "2.2u" / "100p"
 *  - pot:       value "100k log" / "10k lin" / "100k dual"
 *  - transistor/ic/diode: número de parte ("2N3904", "JRC4558D", "1N4148")
 */
window.PEDAL_DB = {

  // Hardware común a casi cualquier build (opcional en el cálculo)
  hardware: [
    { type: "hardware", value: "caja 1590B", qty: 1 },
    { type: "hardware", value: "footswitch 3PDT", qty: 1 },
    { type: "hardware", value: "jack 6.35mm", qty: 2 },
    { type: "hardware", value: "jack DC 2.1mm", qty: 1 },
    { type: "led", value: "LED 5mm", qty: 1 },
  ],

  pedals: [
    {
      id: "bazz-fuss",
      name: "Bazz Fuss",
      brand: "DIY clásico",
      kind: "fuzz",
      difficulty: 1,
      description: "El fuzz más simple que existe: un transistor darlington y un puñado de componentes. Ideal como primer pedal.",
      circuit: [
        { type: "transistor", value: "MPSA13", qty: 1, note: "darlington NPN" },
        { type: "diode", value: "1N4148", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "pot", value: "100k log", qty: 1, note: "volumen" },
      ],
    },
    {
      id: "electra-distortion",
      name: "Electra Distortion",
      brand: "Electra",
      kind: "distorsión",
      difficulty: 1,
      description: "Distorsión de un transistor con recorte por diodos. Muy pocos componentes y suena sorprendentemente bien.",
      circuit: [
        { type: "transistor", value: "2N3904", qty: 1 },
        { type: "diode", value: "1N4148", qty: 2, note: "recorte (probá germanio o LEDs)" },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "2.2k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "pot", value: "100k log", qty: 1, note: "volumen" },
      ],
    },
    {
      id: "lpb-1",
      name: "LPB-1 Linear Power Booster",
      brand: "Electro-Harmonix",
      kind: "boost",
      difficulty: 1,
      description: "Booster lineal de un transistor. Empuja el frente del ampli o de otros pedales.",
      circuit: [
        { type: "transistor", value: "2N5088", qty: 1 },
        { type: "resistor", value: "430k", qty: 1 },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "390", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "pot", value: "100k lin", qty: 1, note: "boost" },
      ],
    },
    {
      id: "rangemaster",
      name: "Rangemaster Treble Booster",
      brand: "Dallas",
      kind: "boost",
      difficulty: 2,
      description: "Treble booster de germanio, el sonido de Brian May y Tony Iommi. Requiere un transistor de germanio con ganancia adecuada.",
      circuit: [
        { type: "transistor", value: "OC44", qty: 1, note: "PNP germanio (OC71/NKT275 sirven)" },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "68k", qty: 1 },
        { type: "resistor", value: "3.9k", qty: 1 },
        { type: "capacitor", value: "4.7n", qty: 1, note: "entrada, define el corte de graves" },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "47u", qty: 1, note: "electrolítico" },
        { type: "pot", value: "10k lin", qty: 1, note: "boost" },
      ],
    },
    {
      id: "fuzz-face",
      name: "Fuzz Face",
      brand: "Dallas Arbiter",
      kind: "fuzz",
      difficulty: 2,
      description: "El fuzz de Hendrix y Gilmour: dos transistores de germanio PNP. Simple de armar, exigente para bias y selección de transistores.",
      circuit: [
        { type: "transistor", value: "AC128", qty: 2, note: "PNP germanio (NKT275); versión silicio: BC108" },
        { type: "resistor", value: "33k", qty: 1 },
        { type: "resistor", value: "8.2k", qty: 1 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "resistor", value: "330", qty: 1 },
        { type: "capacitor", value: "2.2u", qty: 1 },
        { type: "capacitor", value: "22u", qty: 1, note: "electrolítico" },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "pot", value: "1k lin", qty: 1, note: "fuzz" },
        { type: "pot", value: "500k log", qty: 1, note: "volumen" },
      ],
    },
    {
      id: "mxr-distortion-plus",
      name: "Distortion+",
      brand: "MXR",
      kind: "distorsión",
      difficulty: 2,
      description: "Overdrive/distorsión de un opamp con recorte por diodos de germanio. El sonido de Randy Rhoads.",
      circuit: [
        { type: "ic", value: "LM741", qty: 1 },
        { type: "diode", value: "1N34A", qty: 2, note: "germanio (1N60 sirve)" },
        { type: "resistor", value: "1M", qty: 3 },
        { type: "resistor", value: "10k", qty: 2 },
        { type: "resistor", value: "4.7k", qty: 1 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "1n", qty: 1 },
        { type: "capacitor", value: "47n", qty: 1 },
        { type: "capacitor", value: "1u", qty: 2, note: "electrolítico" },
        { type: "pot", value: "500k rev", qty: 1, note: "distortion" },
        { type: "pot", value: "10k log", qty: 1, note: "output" },
      ],
    },
    {
      id: "tube-screamer-ts808",
      name: "Tube Screamer TS808",
      brand: "Ibanez",
      kind: "overdrive",
      difficulty: 3,
      description: "EL overdrive. Recorte simétrico en el lazo de realimentación de un JRC4558D y medios característicos.",
      circuit: [
        { type: "ic", value: "JRC4558D", qty: 1, note: "el 'chip mágico'; RC4558/TL072 funcionan" },
        { type: "transistor", value: "2SC1815", qty: 2, note: "buffers (2N3904 sirve)" },
        { type: "diode", value: "1N914", qty: 2, note: "recorte" },
        { type: "diode", value: "1N4001", qty: 1, note: "protección de polaridad" },
        { type: "resistor", value: "10k", qty: 6 },
        { type: "resistor", value: "4.7k", qty: 2 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "resistor", value: "510k", qty: 2 },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "resistor", value: "51k", qty: 1 },
        { type: "resistor", value: "220", qty: 1 },
        { type: "resistor", value: "470", qty: 1 },
        { type: "capacitor", value: "47n", qty: 2 },
        { type: "capacitor", value: "1u", qty: 3 },
        { type: "capacitor", value: "51p", qty: 1, note: "estabilidad" },
        { type: "capacitor", value: "220n", qty: 1 },
        { type: "capacitor", value: "100n", qty: 1 },
        { type: "capacitor", value: "10u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "47u", qty: 1, note: "electrolítico" },
        { type: "pot", value: "500k rev", qty: 1, note: "drive" },
        { type: "pot", value: "20k lin", qty: 1, note: "tone" },
        { type: "pot", value: "100k log", qty: 1, note: "level" },
      ],
    },
    {
      id: "proco-rat",
      name: "RAT",
      brand: "ProCo",
      kind: "distorsión",
      difficulty: 3,
      description: "Distorsión versátil alrededor del LM308 y su slew rate lento. Del crunch al fuzz con una perilla.",
      circuit: [
        { type: "ic", value: "LM308N", qty: 1, note: "OP07 es el reemplazo moderno" },
        { type: "transistor", value: "2N5458", qty: 1, note: "JFET, buffer de salida" },
        { type: "diode", value: "1N914", qty: 2, note: "recorte" },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "100k", qty: 2 },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "resistor", value: "560", qty: 1 },
        { type: "resistor", value: "47", qty: 1 },
        { type: "capacitor", value: "22n", qty: 2 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "2.2u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "1u", qty: 2 },
        { type: "capacitor", value: "4.7u", qty: 1, note: "electrolítico" },
        { type: "capacitor", value: "3.3n", qty: 1 },
        { type: "capacitor", value: "100p", qty: 1 },
        { type: "capacitor", value: "30p", qty: 1, note: "compensación" },
        { type: "pot", value: "100k log", qty: 1, note: "distortion" },
        { type: "pot", value: "100k lin", qty: 1, note: "filter" },
        { type: "pot", value: "100k log", qty: 1, note: "volume" },
      ],
    },
    {
      id: "big-muff-pi",
      name: "Big Muff Pi",
      brand: "Electro-Harmonix",
      kind: "fuzz",
      difficulty: 3,
      description: "Cuatro etapas de transistores con dos etapas de recorte. Sustain infinito, pared de fuzz. Muchos componentes pero todos comunes.",
      circuit: [
        { type: "transistor", value: "2N5088", qty: 4 },
        { type: "diode", value: "1N4148", qty: 4, note: "recorte (2 pares)" },
        { type: "resistor", value: "100k", qty: 6 },
        { type: "resistor", value: "470k", qty: 3 },
        { type: "resistor", value: "39k", qty: 2 },
        { type: "resistor", value: "12k", qty: 2 },
        { type: "resistor", value: "10k", qty: 4 },
        { type: "resistor", value: "22k", qty: 1 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "resistor", value: "330", qty: 1 },
        { type: "capacitor", value: "100n", qty: 5 },
        { type: "capacitor", value: "1u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "470p", qty: 3, note: "filtro de agudos en cada etapa" },
        { type: "capacitor", value: "4n", qty: 1, note: "tone stack (3.9n sirve)" },
        { type: "capacitor", value: "10n", qty: 1, note: "tone stack" },
        { type: "pot", value: "100k log", qty: 2, note: "sustain y volume" },
        { type: "pot", value: "100k lin", qty: 1, note: "tone" },
      ],
    },
    {
      id: "phase-90",
      name: "Phase 90",
      brand: "MXR",
      kind: "modulación",
      difficulty: 4,
      description: "Phaser de 4 etapas con JFETs como resistencias variables. Requiere matchear los 4 JFETs, pero el resultado vale la pena.",
      circuit: [
        { type: "transistor", value: "2N5952", qty: 4, note: "JFETs matcheados" },
        { type: "ic", value: "TL072", qty: 3, note: "originalmente opamps 741/4558" },
        { type: "resistor", value: "10k", qty: 8 },
        { type: "resistor", value: "24k", qty: 4, note: "etapas de fase" },
        { type: "resistor", value: "22k", qty: 2 },
        { type: "resistor", value: "150k", qty: 2 },
        { type: "resistor", value: "470k", qty: 2 },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "3.9M", qty: 5, note: "bias de los JFETs" },
        { type: "capacitor", value: "47n", qty: 4, note: "etapas de fase" },
        { type: "capacitor", value: "10u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "15u", qty: 1, note: "LFO (electrolítico)" },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "pot", value: "500k rev", qty: 1, note: "speed" },
      ],
    },
    {
      id: "klon-centaur",
      name: "Klon Centaur",
      brand: "Klon",
      kind: "overdrive",
      difficulty: 5,
      description: "El overdrive 'transparente' más mitificado. Charge pump a ±9V, mezcla de señal limpia y recortada con diodos de germanio.",
      circuit: [
        { type: "ic", value: "TL072", qty: 2 },
        { type: "ic", value: "TC1044SCPA", qty: 1, note: "charge pump (ICL7660S sirve)" },
        { type: "diode", value: "1N34A", qty: 2, note: "los famosos diodos de germanio" },
        { type: "diode", value: "1N5817", qty: 2, note: "schottky, fuente" },
        { type: "resistor", value: "10k", qty: 4 },
        { type: "resistor", value: "100k", qty: 5 },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "422k", qty: 1, note: "1% (un 470k aproxima)" },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "68k", qty: 1 },
        { type: "resistor", value: "22k", qty: 1 },
        { type: "resistor", value: "15k", qty: 1 },
        { type: "resistor", value: "5.6k", qty: 1 },
        { type: "resistor", value: "4.7k", qty: 1 },
        { type: "resistor", value: "1.5k", qty: 1 },
        { type: "resistor", value: "560", qty: 1 },
        { type: "capacitor", value: "100n", qty: 4 },
        { type: "capacitor", value: "1u", qty: 3 },
        { type: "capacitor", value: "4.7u", qty: 2, note: "electrolítico" },
        { type: "capacitor", value: "47u", qty: 2, note: "electrolítico, charge pump" },
        { type: "capacitor", value: "68n", qty: 2 },
        { type: "capacitor", value: "390p", qty: 1 },
        { type: "capacitor", value: "820p", qty: 1 },
        { type: "pot", value: "100k dual", qty: 1, note: "gain (doble, curva especial)" },
        { type: "pot", value: "10k lin", qty: 1, note: "treble" },
        { type: "pot", value: "10k log", qty: 1, note: "output" },
      ],
    },
    {
      id: "sho-boost",
      name: "SHO Super Hard-On",
      brand: "ZVEX",
      kind: "boost",
      difficulty: 1,
      description: "Booster de un MOSFET con ganancia enorme y agudos cristalinos. Poquísimos componentes.",
      circuit: [
        { type: "transistor", value: "BS170", qty: 1, note: "MOSFET (2N7000 sirve)" },
        { type: "diode", value: "1N4739", qty: 1, note: "zener 9.1V, protección" },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "10M", qty: 2, note: "bias" },
        { type: "resistor", value: "100", qty: 1 },
        { type: "capacitor", value: "100n", qty: 1 },
        { type: "capacitor", value: "10u", qty: 1 },
        { type: "pot", value: "5k lin", qty: 1, note: "gain ('crackle okay')" },
      ],
    },
    {
      id: "mxr-micro-amp",
      name: "Micro Amp",
      brand: "MXR",
      kind: "boost",
      difficulty: 1,
      description: "Boost limpio de opamp con ganancia ajustable. Ideal para levantar solos.",
      circuit: [
        { type: "ic", value: "TL061", qty: 1, note: "TL071 sirve" },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "470k", qty: 2 },
        { type: "resistor", value: "2.7k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "47p", qty: 1 },
        { type: "capacitor", value: "1u", qty: 1 },
        { type: "capacitor", value: "10u", qty: 1 },
        { type: "pot", value: "500k log", qty: 1, note: "gain" },
      ],
    },
    {
      id: "dod-250",
      name: "Overdrive Preamp 250",
      brand: "DOD",
      kind: "distorsión",
      difficulty: 2,
      description: "Primo hermano del Distortion+: opamp 741 y recorte a masa. El pedal de Yngwie Malmsteen.",
      circuit: [
        { type: "ic", value: "LM741", qty: 1 },
        { type: "diode", value: "1N4148", qty: 2, note: "la versión gris usa silicio; la amarilla, germanio" },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "4.7k", qty: 1 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "47n", qty: 1 },
        { type: "capacitor", value: "1n", qty: 1 },
        { type: "capacitor", value: "1u", qty: 2 },
        { type: "pot", value: "500k log", qty: 1, note: "gain" },
        { type: "pot", value: "100k log", qty: 1, note: "level" },
      ],
    },
    {
      id: "harmonic-percolator",
      name: "Harmonic Percolator",
      brand: "Interfax",
      kind: "fuzz",
      difficulty: 2,
      description: "Fuzz raro y glorioso: un PNP de germanio contra un NPN de silicio. El sonido de Steve Albini.",
      circuit: [
        { type: "transistor", value: "2N404", qty: 1, note: "PNP germanio" },
        { type: "transistor", value: "2N3904", qty: 1, note: "original 2N3565" },
        { type: "diode", value: "1N4148", qty: 2, note: "originales 1N695 (germanio)" },
        { type: "resistor", value: "390k", qty: 1 },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "2.7k", qty: 1 },
        { type: "capacitor", value: "2.2u", qty: 2 },
        { type: "capacitor", value: "100n", qty: 1 },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "470p", qty: 1 },
        { type: "pot", value: "500k lin", qty: 1, note: "harmonics" },
        { type: "pot", value: "100k log", qty: 1, note: "balance" },
      ],
    },
    {
      id: "fuzzrite",
      name: "Fuzzrite",
      brand: "Mosrite",
      kind: "fuzz",
      difficulty: 2,
      description: "Fuzz sesentoso, chillón y rasposo ('In-A-Gadda-Da-Vida'). Dos transistores y a otra cosa.",
      circuit: [
        { type: "transistor", value: "2N3904", qty: 2, note: "versión silicio" },
        { type: "resistor", value: "470k", qty: 2 },
        { type: "resistor", value: "56k", qty: 1 },
        { type: "resistor", value: "10k", qty: 2 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "10n", qty: 2 },
        { type: "capacitor", value: "100n", qty: 1 },
        { type: "capacitor", value: "22n", qty: 1 },
        { type: "pot", value: "500k lin", qty: 1, note: "depth" },
        { type: "pot", value: "500k log", qty: 1, note: "volume" },
      ],
    },
    {
      id: "jordan-bosstone",
      name: "Boss Tone",
      brand: "Jordan",
      kind: "fuzz",
      difficulty: 2,
      description: "Fuzz de los 60 que se enchufaba directo a la guitarra. Grueso, con recorte de diodos.",
      circuit: [
        { type: "transistor", value: "2N3904", qty: 2 },
        { type: "diode", value: "1N4148", qty: 2 },
        { type: "resistor", value: "330k", qty: 1 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "3.3k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "4.7n", qty: 1 },
        { type: "pot", value: "500k log", qty: 1, note: "attack" },
        { type: "pot", value: "100k log", qty: 1, note: "volume" },
      ],
    },
    {
      id: "green-ringer",
      name: "Green Ringer",
      brand: "Dan Armstrong",
      kind: "octavador",
      difficulty: 2,
      description: "Octava superior sin transformador: tres transistores y dos diodos apareados. 'Purple Haze' en una cajita.",
      circuit: [
        { type: "transistor", value: "2N3904", qty: 3 },
        { type: "diode", value: "1N4148", qty: 2, note: "conviene aparearlos" },
        { type: "resistor", value: "470k", qty: 2 },
        { type: "resistor", value: "100k", qty: 2 },
        { type: "resistor", value: "10k", qty: 2 },
        { type: "resistor", value: "4.7k", qty: 2 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 3 },
        { type: "capacitor", value: "1u", qty: 1 },
        { type: "capacitor", value: "10u", qty: 1 },
      ],
    },
    {
      id: "red-llama",
      name: "Red Llama",
      brand: "Way Huge",
      kind: "overdrive",
      difficulty: 2,
      description: "Overdrive con inversores CMOS (CD4049) que recortan como válvulas. Basado en el Tube Sound Fuzz de Craig Anderton.",
      circuit: [
        { type: "ic", value: "CD4049UBE", qty: 1, note: "tiene que ser 'UBE' (unbuffered)" },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "2.2k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "470p", qty: 1 },
        { type: "capacitor", value: "10u", qty: 1 },
        { type: "pot", value: "1M lin", qty: 1, note: "drive" },
        { type: "pot", value: "100k log", qty: 1, note: "volume" },
      ],
    },
    {
      id: "boss-sd1",
      name: "SD-1 Super OverDrive",
      brand: "Boss",
      kind: "overdrive",
      difficulty: 3,
      description: "El pariente de recorte asimétrico del Tube Screamer. Un clásico barato de clonar y de modificar.",
      circuit: [
        { type: "ic", value: "JRC4558D", qty: 1 },
        { type: "transistor", value: "2SC1815", qty: 2, note: "buffers" },
        { type: "diode", value: "1N4148", qty: 3, note: "recorte asimétrico (2+1)" },
        { type: "diode", value: "1N4001", qty: 1, note: "protección" },
        { type: "resistor", value: "10k", qty: 5 },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "100k", qty: 2 },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "33k", qty: 1 },
        { type: "resistor", value: "4.7k", qty: 2 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "resistor", value: "470", qty: 1 },
        { type: "capacitor", value: "47n", qty: 1 },
        { type: "capacitor", value: "18n", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "1u", qty: 2 },
        { type: "capacitor", value: "10u", qty: 2 },
        { type: "capacitor", value: "47u", qty: 1 },
        { type: "capacitor", value: "51p", qty: 1 },
        { type: "pot", value: "1M log", qty: 1, note: "drive" },
        { type: "pot", value: "20k lin", qty: 1, note: "tone" },
        { type: "pot", value: "50k log", qty: 1, note: "level" },
      ],
    },
    {
      id: "boss-ds1",
      name: "DS-1 Distortion",
      brand: "Boss",
      kind: "distorsión",
      difficulty: 3,
      description: "La distorsión naranja de Kurt Cobain y (modificada) de Steve Vai. Etapa de transistor + opamp con recorte simétrico.",
      circuit: [
        { type: "ic", value: "JRC4558D", qty: 1, note: "reemplaza al TA7136 original en clones" },
        { type: "transistor", value: "2SC1815", qty: 2, note: "originales 2SC2240" },
        { type: "diode", value: "1N4148", qty: 2, note: "recorte" },
        { type: "diode", value: "1N4001", qty: 1, note: "protección" },
        { type: "resistor", value: "100k", qty: 4 },
        { type: "resistor", value: "10k", qty: 4 },
        { type: "resistor", value: "22k", qty: 2 },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "4.7k", qty: 2 },
        { type: "resistor", value: "2.2k", qty: 1 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "47n", qty: 3 },
        { type: "capacitor", value: "100n", qty: 1 },
        { type: "capacitor", value: "22n", qty: 1 },
        { type: "capacitor", value: "1u", qty: 2 },
        { type: "capacitor", value: "220p", qty: 1 },
        { type: "capacitor", value: "10u", qty: 1 },
        { type: "capacitor", value: "47u", qty: 1 },
        { type: "pot", value: "100k lin", qty: 1, note: "dist" },
        { type: "pot", value: "20k lin", qty: 1, note: "tone" },
        { type: "pot", value: "100k log", qty: 1, note: "level" },
      ],
    },
    {
      id: "blues-breaker",
      name: "Blues Breaker",
      brand: "Marshall",
      kind: "overdrive",
      difficulty: 3,
      description: "Overdrive suave y dinámico con recorte en el lazo. Base del Analogman King of Tone.",
      circuit: [
        { type: "ic", value: "TL072", qty: 1 },
        { type: "diode", value: "1N4148", qty: 4, note: "recorte, 2 pares en serie" },
        { type: "resistor", value: "100k", qty: 3 },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "10k", qty: 3 },
        { type: "resistor", value: "6.8k", qty: 2 },
        { type: "resistor", value: "27k", qty: 1 },
        { type: "resistor", value: "2.2k", qty: 1 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "10n", qty: 2 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "6.8n", qty: 1 },
        { type: "capacitor", value: "3.3n", qty: 1 },
        { type: "capacitor", value: "1u", qty: 1 },
        { type: "capacitor", value: "47u", qty: 1 },
        { type: "pot", value: "100k dual", qty: 1, note: "gain (doble)" },
        { type: "pot", value: "25k lin", qty: 1, note: "tone" },
        { type: "pot", value: "100k log", qty: 1, note: "volume" },
      ],
    },
    {
      id: "guvnor",
      name: "Guv'nor",
      brand: "Marshall",
      kind: "distorsión",
      difficulty: 3,
      description: "Distorsión estilo Marshall en pedal, con tone stack completo de graves, medios y agudos.",
      circuit: [
        { type: "ic", value: "TL072", qty: 1 },
        { type: "diode", value: "1N4148", qty: 2, note: "recorte" },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "100k", qty: 3 },
        { type: "resistor", value: "22k", qty: 2 },
        { type: "resistor", value: "10k", qty: 3 },
        { type: "resistor", value: "4.7k", qty: 1 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "capacitor", value: "100n", qty: 3 },
        { type: "capacitor", value: "22n", qty: 2 },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "4.7n", qty: 1 },
        { type: "capacitor", value: "1u", qty: 2 },
        { type: "capacitor", value: "47u", qty: 1 },
        { type: "pot", value: "100k log", qty: 2, note: "gain y volume" },
        { type: "pot", value: "100k lin", qty: 3, note: "bass, middle, treble" },
      ],
    },
    {
      id: "phase-45",
      name: "Phase 45",
      brand: "MXR",
      kind: "modulación",
      difficulty: 3,
      description: "El hermano menor del Phase 90: dos etapas de fase, más sutil. Solo hay que matchear 2 JFETs.",
      circuit: [
        { type: "transistor", value: "2N5952", qty: 2, note: "JFETs matcheados" },
        { type: "ic", value: "LM741", qty: 2, note: "o un TL072 doble adaptando" },
        { type: "resistor", value: "470k", qty: 4 },
        { type: "resistor", value: "10k", qty: 6 },
        { type: "resistor", value: "22k", qty: 2 },
        { type: "resistor", value: "150k", qty: 1 },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "3.9M", qty: 3, note: "bias JFETs" },
        { type: "capacitor", value: "47n", qty: 2 },
        { type: "capacitor", value: "10u", qty: 2 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "15u", qty: 1, note: "LFO" },
        { type: "pot", value: "500k rev", qty: 1, note: "speed" },
      ],
    },
    {
      id: "dyna-comp",
      name: "Dyna Comp",
      brand: "MXR",
      kind: "compresor",
      difficulty: 4,
      description: "El compresor de Nashville, alrededor del OTA CA3080. El chip está discontinuado pero se consigue.",
      circuit: [
        { type: "ic", value: "CA3080", qty: 1, note: "OTA, discontinuado — verificar antes de comprar" },
        { type: "transistor", value: "2N3904", qty: 4 },
        { type: "diode", value: "1N4148", qty: 2 },
        { type: "resistor", value: "10k", qty: 4 },
        { type: "resistor", value: "150k", qty: 2 },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "15k", qty: 1 },
        { type: "resistor", value: "5.6k", qty: 1 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "capacitor", value: "1u", qty: 3 },
        { type: "capacitor", value: "10u", qty: 2 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "47p", qty: 1 },
        { type: "capacitor", value: "5.6n", qty: 1 },
        { type: "pot", value: "500k log", qty: 1, note: "sustain" },
        { type: "pot", value: "50k log", qty: 1, note: "output" },
      ],
    },
    {
      id: "orange-squeezer",
      name: "Orange Squeezer",
      brand: "Dan Armstrong",
      kind: "compresor",
      difficulty: 3,
      description: "Compresor squishy de JFETs, favorito del funk y el country. Sin perillas: se ajusta con un trimmer interno.",
      circuit: [
        { type: "ic", value: "LM1458", qty: 1, note: "4558 sirve" },
        { type: "transistor", value: "2N5457", qty: 2, note: "JFETs" },
        { type: "diode", value: "1N4148", qty: 1 },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "100k", qty: 1 },
        { type: "resistor", value: "10k", qty: 2 },
        { type: "resistor", value: "4.7k", qty: 1 },
        { type: "resistor", value: "2.7k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "4.7u", qty: 2 },
        { type: "capacitor", value: "47u", qty: 1 },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "pot", value: "50k lin", qty: 1, note: "trimmer interno de bias" },
      ],
    },
    {
      id: "crybaby-gcb95",
      name: "Cry Baby GCB-95",
      brand: "Dunlop",
      kind: "wah",
      difficulty: 3,
      description: "El wah de siempre. El circuito es simple; lo específico es el inductor y la carcasa con pedal de expresión.",
      circuit: [
        { type: "transistor", value: "2N3904", qty: 2, note: "originales MPSA18" },
        { type: "hardware", value: "inductor 500mH", qty: 1, note: "el corazón del wah" },
        { type: "hardware", value: "carcasa wah", qty: 1, note: "con mecanismo de pedal" },
        { type: "resistor", value: "68k", qty: 1 },
        { type: "resistor", value: "1.5k", qty: 1 },
        { type: "resistor", value: "33k", qty: 1 },
        { type: "resistor", value: "82k", qty: 1 },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "22k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "470", qty: 1 },
        { type: "capacitor", value: "10n", qty: 2 },
        { type: "capacitor", value: "4.7u", qty: 1 },
        { type: "capacitor", value: "220n", qty: 1 },
        { type: "capacitor", value: "100n", qty: 1 },
        { type: "pot", value: "100k log", qty: 1, note: "pot de wah (tipo ICAR)" },
      ],
    },
    {
      id: "ea-tremolo",
      name: "EA Tremolo",
      brand: "DIY clásico",
      kind: "modulación",
      difficulty: 2,
      description: "Trémolo simple y muy popular en el DIY: un JFET como elemento de volumen y un LFO de dos transistores.",
      circuit: [
        { type: "transistor", value: "2N5457", qty: 1, note: "JFET" },
        { type: "transistor", value: "2N3904", qty: 2, note: "LFO" },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "470k", qty: 2 },
        { type: "resistor", value: "100k", qty: 2 },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "10k", qty: 2 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "10u", qty: 2 },
        { type: "capacitor", value: "4.7u", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "1u", qty: 1 },
        { type: "pot", value: "500k lin", qty: 1, note: "speed" },
        { type: "pot", value: "50k lin", qty: 1, note: "depth" },
      ],
    },
    {
      id: "super-fuzz",
      name: "Super-Fuzz",
      brand: "Univox",
      kind: "fuzz",
      difficulty: 4,
      description: "Fuzz con octava superior y recorte de germanio, seis transistores. El sonido de Pete Townshend.",
      circuit: [
        { type: "transistor", value: "2SC828", qty: 6, note: "C945/C1815 sirven" },
        { type: "diode", value: "1N34A", qty: 2, note: "recorte germanio" },
        { type: "resistor", value: "100k", qty: 6 },
        { type: "resistor", value: "47k", qty: 4 },
        { type: "resistor", value: "10k", qty: 5 },
        { type: "resistor", value: "22k", qty: 2 },
        { type: "resistor", value: "470k", qty: 2 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "resistor", value: "330k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 4 },
        { type: "capacitor", value: "10u", qty: 2 },
        { type: "capacitor", value: "4.7u", qty: 2 },
        { type: "capacitor", value: "1u", qty: 2 },
        { type: "capacitor", value: "2.2n", qty: 1 },
        { type: "pot", value: "50k lin", qty: 1, note: "expand" },
        { type: "pot", value: "100k log", qty: 1, note: "balance" },
      ],
    },
    {
      id: "tone-bender-mk2",
      name: "Tone Bender MkII",
      brand: "Sola Sound",
      kind: "fuzz",
      difficulty: 3,
      description: "Tres transistores de germanio: el fuzz de Jimmy Page. Como el Fuzz Face, pide germanio seleccionado.",
      circuit: [
        { type: "transistor", value: "AC128", qty: 3, note: "PNP germanio (OC75 originales)" },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "100k", qty: 2 },
        { type: "resistor", value: "47k", qty: 1 },
        { type: "resistor", value: "8.2k", qty: 1 },
        { type: "resistor", value: "10k", qty: 1 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "4.7u", qty: 1 },
        { type: "capacitor", value: "47u", qty: 1 },
        { type: "pot", value: "1k lin", qty: 1, note: "attack" },
        { type: "pot", value: "100k log", qty: 1, note: "level" },
      ],
    },
    {
      id: "small-clone",
      name: "Small Clone",
      brand: "Electro-Harmonix",
      kind: "modulación",
      difficulty: 5,
      description: "El chorus de Nirvana. Necesita un BBD MN3007 y su clock; el resto es circuitería estándar.",
      circuit: [
        { type: "ic", value: "MN3007", qty: 1, note: "BBD — comprar específicamente" },
        { type: "ic", value: "CD4047", qty: 1, note: "clock" },
        { type: "ic", value: "JRC4558D", qty: 2 },
        { type: "resistor", value: "10k", qty: 6 },
        { type: "resistor", value: "100k", qty: 4 },
        { type: "resistor", value: "47k", qty: 3 },
        { type: "resistor", value: "22k", qty: 2 },
        { type: "resistor", value: "470k", qty: 2 },
        { type: "resistor", value: "1M", qty: 1 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "capacitor", value: "100n", qty: 4 },
        { type: "capacitor", value: "10n", qty: 2 },
        { type: "capacitor", value: "1n", qty: 2 },
        { type: "capacitor", value: "47p", qty: 2 },
        { type: "capacitor", value: "10u", qty: 3 },
        { type: "capacitor", value: "1u", qty: 2 },
        { type: "capacitor", value: "100u", qty: 1 },
        { type: "pot", value: "100k lin", qty: 1, note: "rate" },
      ],
    },
    {
      id: "rebote-delay",
      name: "Rebote Delay (PT2399)",
      brand: "Tonepad",
      kind: "delay",
      difficulty: 3,
      description: "Delay sobre el baratísimo PT2399: el proyecto de delay DIY más armado del mundo.",
      circuit: [
        { type: "ic", value: "PT2399", qty: 1 },
        { type: "ic", value: "TL072", qty: 1 },
        { type: "resistor", value: "10k", qty: 6 },
        { type: "resistor", value: "100k", qty: 2 },
        { type: "resistor", value: "15k", qty: 2 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "capacitor", value: "100n", qty: 6 },
        { type: "capacitor", value: "10u", qty: 2 },
        { type: "capacitor", value: "47u", qty: 1 },
        { type: "capacitor", value: "1u", qty: 2 },
        { type: "capacitor", value: "5.6n", qty: 2 },
        { type: "capacitor", value: "100p", qty: 1 },
        { type: "pot", value: "50k lin", qty: 3, note: "delay, repeats y mix" },
      ],
    },
    {
      id: "timmy",
      name: "Timmy",
      brand: "Paul Cochrane",
      kind: "overdrive",
      difficulty: 3,
      description: "Overdrive 'transparente' moderno con graves y agudos interactivos. Muy clonado (Vemuram Jan Ray).",
      circuit: [
        { type: "ic", value: "JRC4559", qty: 1, note: "4558/TL072 sirven" },
        { type: "diode", value: "1N4148", qty: 4, note: "recorte asimétrico" },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "470k", qty: 1 },
        { type: "resistor", value: "33k", qty: 1 },
        { type: "resistor", value: "10k", qty: 2 },
        { type: "resistor", value: "4.7k", qty: 1 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "47n", qty: 1 },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "1n", qty: 1 },
        { type: "capacitor", value: "1u", qty: 1 },
        { type: "capacitor", value: "47u", qty: 1 },
        { type: "pot", value: "500k log", qty: 1, note: "gain" },
        { type: "pot", value: "10k lin", qty: 2, note: "bass y treble" },
        { type: "pot", value: "100k log", qty: 1, note: "volume" },
      ],
    },
    {
      id: "fulltone-ocd",
      name: "OCD",
      brand: "Fulltone",
      kind: "overdrive",
      difficulty: 3,
      description: "Overdrive con recorte de MOSFETs que responde como un ampli. Uno de los más vendidos de los 2000.",
      circuit: [
        { type: "ic", value: "TL082", qty: 1, note: "TL072 sirve" },
        { type: "transistor", value: "2N7000", qty: 2, note: "MOSFETs de recorte" },
        { type: "diode", value: "1N4001", qty: 1, note: "protección" },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "100k", qty: 2 },
        { type: "resistor", value: "33k", qty: 1 },
        { type: "resistor", value: "10k", qty: 2 },
        { type: "resistor", value: "2.2k", qty: 1 },
        { type: "resistor", value: "1k", qty: 1 },
        { type: "capacitor", value: "100n", qty: 2 },
        { type: "capacitor", value: "22n", qty: 1 },
        { type: "capacitor", value: "10n", qty: 1 },
        { type: "capacitor", value: "100p", qty: 1 },
        { type: "capacitor", value: "1u", qty: 1 },
        { type: "capacitor", value: "47u", qty: 1 },
        { type: "pot", value: "1M log", qty: 1, note: "drive" },
        { type: "pot", value: "10k lin", qty: 1, note: "tone" },
        { type: "pot", value: "500k log", qty: 1, note: "volume" },
      ],
    },
    {
      id: "colorsound-power-boost",
      name: "Power Boost",
      brand: "Colorsound",
      kind: "overdrive",
      difficulty: 3,
      description: "Boost/overdrive de tres transistores con control de graves y agudos. El secreto de David Gilmour en los 70.",
      circuit: [
        { type: "transistor", value: "BC549", qty: 3, note: "originales BC184" },
        { type: "resistor", value: "470k", qty: 2 },
        { type: "resistor", value: "100k", qty: 3 },
        { type: "resistor", value: "22k", qty: 2 },
        { type: "resistor", value: "10k", qty: 2 },
        { type: "resistor", value: "3.3k", qty: 1 },
        { type: "resistor", value: "1k", qty: 2 },
        { type: "resistor", value: "330", qty: 1 },
        { type: "capacitor", value: "100n", qty: 3 },
        { type: "capacitor", value: "10n", qty: 2 },
        { type: "capacitor", value: "2.2n", qty: 1 },
        { type: "capacitor", value: "4.7u", qty: 2 },
        { type: "capacitor", value: "100u", qty: 1 },
        { type: "pot", value: "100k lin", qty: 2, note: "bass y treble" },
        { type: "pot", value: "10k log", qty: 1, note: "gain" },
        { type: "pot", value: "100k log", qty: 1, note: "volume" },
      ],
    },
    {
      id: "boss-ce2",
      name: "CE-2 Chorus",
      brand: "Boss",
      kind: "modulación",
      difficulty: 5,
      description: "EL chorus analógico ochentoso. BBD MN3007 + clock MN3101; el resto es circuitería estándar pero abundante.",
      circuit: [
        { type: "ic", value: "MN3007", qty: 1, note: "BBD" },
        { type: "ic", value: "MN3101", qty: 1, note: "clock del BBD" },
        { type: "ic", value: "JRC4558D", qty: 2 },
        { type: "transistor", value: "2SC1815", qty: 3 },
        { type: "resistor", value: "10k", qty: 8 },
        { type: "resistor", value: "100k", qty: 6 },
        { type: "resistor", value: "47k", qty: 4 },
        { type: "resistor", value: "22k", qty: 3 },
        { type: "resistor", value: "1M", qty: 2 },
        { type: "resistor", value: "1k", qty: 3 },
        { type: "capacitor", value: "100n", qty: 5 },
        { type: "capacitor", value: "47n", qty: 2 },
        { type: "capacitor", value: "10n", qty: 3 },
        { type: "capacitor", value: "1n", qty: 2 },
        { type: "capacitor", value: "220p", qty: 2 },
        { type: "capacitor", value: "10u", qty: 3 },
        { type: "capacitor", value: "1u", qty: 3 },
        { type: "capacitor", value: "47u", qty: 2 },
        { type: "pot", value: "100k lin", qty: 2, note: "rate y depth" },
      ],
    },
  ],
};
